name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (metadata only)
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@14.225.198.220 '
            set -e

            # Clone nếu repo chưa có
            if [ ! -d /root/Elavia/Client/.git ]; then
              mkdir -p /root/Elavia
              cd /root/Elavia
              git clone https://github.com/hoanghiep2625/Elavia-Client.git Client
            fi

            cd /root/Elavia/Client

            # Đặt lại remote cho chắc chắn (đổi URL repo nếu khác)
            git remote set-url origin https://github.com/hoanghiep2625/Elavia-Client.git

            # Lấy dữ liệu mới nhất, không merge
            git fetch --all --prune

            # Đảm bảo đứng trên đúng nhánh
            git checkout master

            # Ép local = remote, tránh conflict .DS_Store, v.v.
            git reset --hard origin/master
            git clean -fd

            # Cài deps & build (dùng npm ci nếu có lockfile để reproducible)
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi

            npm run build

            # Restart PM2
            pm2 restart Client-Elavia --update-env || pm2 start "npm run start" --name Client-Elavia
            pm2 save
          '
