name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (metadata only)
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@14.225.198.220 '
          set -e

          # Clone nếu repo chưa tồn tại
          if [ ! -d /root/Elavia/Client/.git ]; then
            mkdir -p /root/Elavia
            cd /root/Elavia
            git clone https://github.com/hoanghiep2625/Elavia-Client.git Client
          fi

          cd /root/Elavia/Client

          # 1) HỦY MERGE DỞ + DỌN RÁC
          git merge --abort || true
          git reset --hard
          git clean -fd

          # 2) ĐỒNG BỘ REMOTE & LẤY NHÁNH MỚI NHẤT
          git remote set-url origin https://github.com/hoanghiep2625/Elavia-Client.git
          git fetch --all --prune

          # 3) NHÁNH ĐÚNG GIỜ LÀ "main" (vì origin/master đã bị xóa)
          git checkout main || git checkout -b main
          git reset --hard origin/main
          git clean -fd

          # 4) CÀI & BUILD
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          npm run build

          # 5) KHỞI ĐỘNG LẠI PM2
          pm2 restart Client-Elavia --update-env || pm2 start "npm run start" --name Client-Elavia
          pm2 save
          '
