name: Deploy to VPS

on:
  push:
    branches:
      - master  # Hoặc nhánh bạn muốn trigger deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
              ssh -o StrictHostKeyChecking=no root@14.225.198.220 'cd /home/root/Ivymoda/Client && git pull && npm install && npm run build && pm2 restart your-app'
